<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Choisir</name>
   <tag></tag>
   <elementGuidId>2d57f40b-6260-4c6f-9026-0dbfdf62b6a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='retailer-card-label-1002']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#retailer-card-label-1002</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7beba71e-c9ec-4f23-ad33-cbd95b897edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>retailer-card-label-1002</value>
      <webElementGuid>82e64ce6-0f69-4d33-8b5d-dedd8c1e8691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>862ef1d1-710e-465a-8867-5aef75099478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choisir</value>
      <webElementGuid>05ef343c-59b7-4a4a-9811-b7333f7963d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;retailer-card-label-1002&quot;)</value>
      <webElementGuid>b7aeb4e6-a1c7-490c-be2e-2992b7e93ee7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='retailer-card-label-1002']</value>
      <webElementGuid>862b665f-7951-4140-b81e-8e1be328d073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area-59']/ol/li[2]/div/div[2]/button/span</value>
      <webElementGuid>1e67c1ff-f123-4042-b961-342da146b853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Commande disponible dans 30 minutes'])[32]/following::span[1]</value>
      <webElementGuid>bbf78b71-539f-40de-b312-77cae27f5bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Croix'])[1]/following::span[2]</value>
      <webElementGuid>8a94adf1-bd88-459c-914b-76d687c4862c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plus d’info'])[32]/preceding::span[1]</value>
      <webElementGuid>816b497a-3937-46d1-9579-2758a6ade077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hallennes Lez Haubourdin'])[1]/preceding::span[2]</value>
      <webElementGuid>71dccf93-d1af-4bfb-87fa-176ab1af6104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/div[2]/ol/li[2]/div/div[2]/button/span</value>
      <webElementGuid>d6b340ac-b67a-4901-af1b-c403b6d6a2c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'retailer-card-label-1002' and (text() = 'Choisir' or . = 'Choisir')]</value>
      <webElementGuid>3ad0583b-b6b6-461a-8b73-c0ddbdf4b660</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
