<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_46,14</name>
   <tag></tag>
   <elementGuidId>8d12ed88-8652-4f1a-8139-9531df35b39a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/header/div/div/div[3]/a[3]/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a0ab5f92-6ef4-45e9-936b-736fe33e4a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>3ef6d9c9-5f06-4b6e-8732-b91656fdc0ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>46,14€</value>
      <webElementGuid>87331e8e-3234-47cb-a31b-70abdcd70f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;chronodrive-app&quot;]/header[@class=&quot;site-header&quot;]/div[@class=&quot;header-banner&quot;]/div[@class=&quot;ui-wrapper&quot;]/div[@class=&quot;header-actions&quot;]/a[@class=&quot;cta -cart&quot;]/span[@class=&quot;value&quot;]</value>
      <webElementGuid>0a7187a8-ea58-4999-80b1-35482eed464a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/header/div/div/div[3]/a[3]/span[2]</value>
      <webElementGuid>f30def58-f539-47b8-9c27-b7a86de6240e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='articles'])[1]/following::span[1]</value>
      <webElementGuid>2fa3398b-c4a0-4951-be71-6cd6c82b031b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Compte'])[1]/following::span[5]</value>
      <webElementGuid>0bb09d3e-594b-40ba-9e80-676c78abf7d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trouver mon drive'])[1]/preceding::span[2]</value>
      <webElementGuid>c1f62dea-0934-466c-99b5-8260eebcc733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/span[2]</value>
      <webElementGuid>014dd6ff-31bd-4bf1-8ed5-9ba62c26dc4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '46,14€' or . = '46,14€')]</value>
      <webElementGuid>1bd8c92b-3b89-4f93-8a83-b1d8addba812</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
