<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ajouter au panier  Infusion de fruit_bed88e</name>
   <tag></tag>
   <elementGuidId>97abdb19-c0ea-49d7-9412-bd01aeebfc89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[231]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.cart-stepper-add.cta-cart</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d4cbf931-ab59-405b-813a-c0b71db0527d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3d8f0fc8-fcec-4352-abc3-b4e1965f1e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cart-stepper-add cta-cart</value>
      <webElementGuid>940c7773-ef90-477e-9dcf-8b93de6d6cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Ajouter au panier  Infusion de fruits rouges</value>
      <webElementGuid>3babc8dc-a889-4f7f-8377-65dd8e135af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;line-295006&quot;)/article[@class=&quot;product-card product-grid-card -layout-fluid -clickable&quot;]/div[@class=&quot;card-inner&quot;]/div[@class=&quot;card-content&quot;]/div[@class=&quot;card-main&quot;]/div[@class=&quot;product-actions -variant-1&quot;]/div[@class=&quot;product-actions-info&quot;]/div[@class=&quot;cart-stepper&quot;]/p[@class=&quot;cart-stepper-container&quot;]/button[@class=&quot;cart-stepper-add cta-cart&quot;]</value>
      <webElementGuid>89ec4ee3-d7b7-46b3-a1e0-f78d1a265047</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[231]</value>
      <webElementGuid>39e4f59c-85db-476f-ab11-89685467748d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='line-295006']/article/div/div/div[2]/div[2]/div[2]/div/p/button[2]</value>
      <webElementGuid>85102465-b8bb-461a-b153-0dfa31406742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cagnotté'])[1]/following::button[2]</value>
      <webElementGuid>27fd4d88-f37c-458e-a439-595f94f17a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Juste pour vous'])[1]/preceding::button[1]</value>
      <webElementGuid>ef11633e-e6b3-44c8-8956-dbc02da6834c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/button[2]</value>
      <webElementGuid>9b260d4b-c90a-477a-ba44-abd85bac87d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Ajouter au panier  Infusion de fruits rouges' or . = ' Ajouter au panier  Infusion de fruits rouges')]</value>
      <webElementGuid>68b90ae9-8e84-41bf-9714-afeb7e6a4be4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
