<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ol</name>
   <tag></tag>
   <elementGuidId>e0b5e837-d586-4f94-9d37-0b0130829763</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/div/div/div/div[2]/div/div/div/div/div/div/div[3]/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>52395124-302b-4a48-9b58-c8b7048600a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>41b671ff-21da-456c-b1c8-14aeff6f00e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Olé</value>
      <webElementGuid>7fef110d-d61a-4f98-ab7f-e18be6d3df52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;product-shop-page page-layout -full-height&quot;]/div[@class=&quot;catalog-listing&quot;]/div[@class=&quot;header&quot;]/div[@class=&quot;catalog-filters-ghost&quot;]/div[@class=&quot;catalog-filters&quot;]/div[@class=&quot;ui-wrapper -desktop-only&quot;]/div[@class=&quot;ui-slider -size-s -active -controls -desktop-only -offset-mobile -scrim&quot;]/div[@class=&quot;ui-slider-content&quot;]/div[@class=&quot;ui-slider-inner swiper-initialized swiper-horizontal swiper-pointer-events swiper-watch-progress swiper-backface-hidden&quot;]/div[@class=&quot;swiper-wrapper ui-slider-wrapper&quot;]/div[@class=&quot;swiper-slide ui-slider-slide swiper-slide-visible&quot;]/div[@class=&quot;filter-item&quot;]/button[@class=&quot;ui-cta -layout-rounded -size-m -variant-2&quot;]/span[@class=&quot;label&quot;]</value>
      <webElementGuid>a4ae667f-5c66-49fb-87b9-16390f2e8161</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div/div/div/div[2]/div/div/div/div/div/div/div[3]/div/button/span</value>
      <webElementGuid>b81ad42a-89d1-4ac9-8a1d-105027e5828f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anti-gaspi'])[1]/following::span[1]</value>
      <webElementGuid>f93a5e12-bcc3-4573-9fcf-3c83d4e3df29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tous'])[1]/following::span[2]</value>
      <webElementGuid>12ecd4fe-ccec-410a-b249-ca65f1423eb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nouveautés'])[2]/preceding::span[1]</value>
      <webElementGuid>516d014b-7176-4199-bbc2-8afca4ea83a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bio'])[3]/preceding::span[2]</value>
      <webElementGuid>f8cbb0d5-4feb-4da4-9bba-6e6542f28728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[3]/div/button/span</value>
      <webElementGuid>7c73afe5-24a9-4eac-9b4d-f7e4e3315891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Olé' or . = 'Olé')]</value>
      <webElementGuid>31db449f-18cb-4d23-991a-165b7fa17635</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
