<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Oui</name>
   <tag></tag>
   <elementGuidId>12f6103a-f08d-40c5-a6af-245e7f0b0dfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vue-portal-target-anBvVME68_1CKvB1oAhqt']/div[3]/div/div/div/dl[2]/dd/article/div/div/ul/li/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>267aabf3-df9e-4119-9365-27d8a935798b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ff4f5f44-7919-411f-a9e4-fc560a9596a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Oui</value>
      <webElementGuid>4333a68a-3600-47dc-9cfc-9dc4069c195c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vue-portal-target-anBvVME68_1CKvB1oAhqt&quot;)/div[3]/div[@class=&quot;overlay-modal mini-cart -variant-3 -scrolling&quot;]/div[@class=&quot;overlay-inner&quot;]/div[@class=&quot;overlay-content&quot;]/dl[@class=&quot;product-group -variant-1&quot;]/dd[1]/article[@class=&quot;product-card -layout-landscape -clickable&quot;]/div[@class=&quot;card-layer -variant-1&quot;]/div[@class=&quot;layer-content&quot;]/ul[@class=&quot;layer-actions&quot;]/li[1]/button[@class=&quot;ui-cta -layout-outline -size-m -variant-1&quot;]/span[@class=&quot;label&quot;]</value>
      <webElementGuid>501eb0d1-f361-4651-afe4-d2734ddd4acb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vue-portal-target-anBvVME68_1CKvB1oAhqt']/div[3]/div/div/div/dl[2]/dd/article/div/div/ul/li/button/span</value>
      <webElementGuid>c3052b28-0b24-48b6-958d-bf92f22727b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Epicerie sucrée'])[4]/following::span[1]</value>
      <webElementGuid>e2ead1cb-ef46-4a25-8fcd-afde2fb19fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Voir les produits suggérés'])[7]/following::span[2]</value>
      <webElementGuid>1c2bd861-a7b3-477d-ba5e-8de3703c465d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non'])[4]/preceding::span[1]</value>
      <webElementGuid>1428d29c-71be-4c31-b33a-a8adbeb19c57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dl[2]/dd/article/div/div/ul/li/button/span</value>
      <webElementGuid>1e9159e7-6387-4c71-acff-8ff0a4dacbe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Oui' or . = 'Oui')]</value>
      <webElementGuid>c72ca8e1-85fc-40bc-9aab-292ac7ee51c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
