<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rechercher un code postal ou une vill_cf4ae2</name>
   <tag></tag>
   <elementGuidId>f23e8553-5099-4fa9-a422-a75afdb882ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='locator-search-term']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#locator-search-term</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>08cbd9c8-eb72-483f-8486-af07a59741a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>locator-search-term</value>
      <webElementGuid>112842d7-3c4b-42a8-847c-75c3e7ccc2ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>locator-search-term-suggestion</value>
      <webElementGuid>4d484722-badb-4e49-aa29-5f9f15a96bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>locator-search-term-message</value>
      <webElementGuid>d3889a35-d101-40d8-90ca-51d1b3faddc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cb70687a-cff1-46ff-a553-8a2d8ca9866e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>9603e2bc-a12e-43d8-8d7a-76b43cc63f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>postal-code</value>
      <webElementGuid>0f7cd3c2-3d5a-4867-8bfe-009fefc822f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search-term</value>
      <webElementGuid>e2e3b278-45af-4707-97a2-068652cdb124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Code postal, ville…</value>
      <webElementGuid>99d79341-7b43-4597-8b5a-22a4920168c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f78888ef-ff4c-4680-86fb-07dcc3a4a871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focus-visible</value>
      <webElementGuid>016d6549-7cd6-4c1a-adb5-2ec5a807c345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locator-search-term&quot;)</value>
      <webElementGuid>68b56971-4ef3-42f8-8402-0e42bbd81447</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='locator-search-term']</value>
      <webElementGuid>4dff660a-75a4-46b0-8ed2-097b1f4f6f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div/div/div[2]/div/div/div/div/div/form/div/div/input</value>
      <webElementGuid>a4e27ea4-9400-4681-b840-d6b0bfb4b041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/form/div/div/input</value>
      <webElementGuid>04a07eb0-f4e6-4e96-b9da-6e414bc98938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'locator-search-term' and @name = 'search-term' and @placeholder = 'Code postal, ville…' and @type = 'text']</value>
      <webElementGuid>8f21992c-ce4c-489b-b432-ac7a8bb173a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
