<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>33020302-51d5-4413-8ba7-10f1e635f6a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='line-509328']/article/div[2]/div/div/span[3]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot; Raisin blanc sans pépins cat 1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d76e6dfd-78cd-4091-b06a-fb5c081a1387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static1.chronodrive.com/img/PM/P/0/28/0P_509328.gif</value>
      <webElementGuid>e13077eb-38ec-4535-ac57-e7dfc7d257fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>32b8e9b0-e0da-47be-a513-5f3265145bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value> Raisin blanc sans pépins cat 1</value>
      <webElementGuid>a2606a31-4755-40d6-9941-a23e5e3021a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>eager</value>
      <webElementGuid>bacc67f9-d4fb-4e13-81f6-91f3dbc24da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>aa10350c-8b1c-4ac0-b9fe-b1675ff179d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>84778352-c62b-4de1-a5a7-f47e2777ec93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;line-509328&quot;)/article[@class=&quot;product-card product-grid-card -layout-fluid -clickable&quot;]/div[@class=&quot;card-inner&quot;]/div[@class=&quot;card-content&quot;]/div[@class=&quot;card-extra&quot;]/span[@class=&quot;media&quot;]/img[1]</value>
      <webElementGuid>3790db3e-eb99-4142-87ff-fb804e387320</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='line-509328']/article/div[2]/div/div/span[3]/img</value>
      <webElementGuid>2f4dc909-cee8-4a65-8ea8-8fd9ee07a132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ITALIE'])[1]/following::img[1]</value>
      <webElementGuid>02e40ddd-2e49-4a8d-84a9-bdcc63ebaa67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non'])[1]/following::img[1]</value>
      <webElementGuid>617c5058-dadc-41f0-9b45-c0b754917499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frais'])[1]/preceding::img[1]</value>
      <webElementGuid>a31df83e-c674-408f-acfe-4bcec7988204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt=' Raisin blanc sans pépins cat 1']</value>
      <webElementGuid>efb93be2-df96-4816-847a-d9fa3bbf8b2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/img</value>
      <webElementGuid>74f5aceb-6bbf-4137-9e3b-9a239c2ffde5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://static1.chronodrive.com/img/PM/P/0/28/0P_509328.gif' and @alt = ' Raisin blanc sans pépins cat 1']</value>
      <webElementGuid>6e6f9614-2f8d-4ea8-a111-d3281e48e7c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
