<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Forte affluence_timeslot-items</name>
   <tag></tag>
   <elementGuidId>2303e92c-bd2b-4cf2-b4a4-bab84ba3c0b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='slot-7297829']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#slot-7297829</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41fc284c-1eec-474f-bcdc-fcddaf98ca00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>slot-7297829</value>
      <webElementGuid>0dbe7b6f-a327-4d56-8e3b-d61b0fb03fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>timeslot-items</value>
      <webElementGuid>a313c31e-3e26-40e6-81a3-51ad091b9a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>9ea6fcc0-6a45-4bb7-a9ba-b044e56763c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>7297829</value>
      <webElementGuid>7fe449c0-b902-4dcd-86c2-ede194547016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slot-7297829&quot;)</value>
      <webElementGuid>699c1d06-3aa7-4a85-a82c-328abebb2c67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='slot-7297829']</value>
      <webElementGuid>b41aadbc-572f-4a1b-b44b-1f24e3e5700f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='timeslot-form']/ul/li[9]/label/span/input</value>
      <webElementGuid>86fcaee3-52c6-49aa-b27b-c7110e012a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forte affluence'])[4]/following::input[4]</value>
      <webElementGuid>77a63e7a-9bd3-45cb-b2c5-3a491225e9ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forte affluence'])[3]/following::input[5]</value>
      <webElementGuid>d23b8430-1306-47ee-9d62-14ec1de12381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/label/span/input</value>
      <webElementGuid>5874e04a-db6f-42bc-a299-259605eec465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'slot-7297829' and @name = 'timeslot-items' and @type = 'radio']</value>
      <webElementGuid>b09e0a9b-cc0e-4d37-854d-49dca1669269</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
