<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_conditions gnrales de vente_alcohol-legals</name>
   <tag></tag>
   <elementGuidId>cbe40fd6-f25e-4eb2-aab6-83f8265f0be5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='alcohol-legals']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#alcohol-legals</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71855444-06d4-4950-a9de-df57a48be239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alcohol-legals</value>
      <webElementGuid>e626ed08-e89b-49ea-a145-01a7753d810c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>alcohol-legals</value>
      <webElementGuid>307e8d1c-1434-439b-a9d7-320eda9a2e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>89916db9-42b8-40d0-b74a-837e29204185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f222f6f2-ef57-44b3-9e2d-b610d8f18377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alcohol-legals&quot;)</value>
      <webElementGuid>a93b1328-f92b-4192-a109-de40f30a1506</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='alcohol-legals']</value>
      <webElementGuid>b6ccb32f-2c9c-469e-a567-3c2b744dbc10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/main/div/form/div/div/div/div[3]/div[2]/div/div/div/div/div[2]/span/span/input</value>
      <webElementGuid>b59d3b40-dc4d-48c0-bbe4-f93378cc4baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='conditions générales de vente.'])[1]/following::input[1]</value>
      <webElementGuid>e227f000-b7d7-41be-9259-eb8e18a607f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Je certifie avoir plus de 18 ans (âge minimum pour acheter de l’alcool).'])[1]/preceding::input[1]</value>
      <webElementGuid>525eff36-9dbc-4387-9d01-41288d63b091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terminer ma commande'])[1]/preceding::input[1]</value>
      <webElementGuid>765b3f1d-5cc1-4125-9eac-ef5862510b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/span/input</value>
      <webElementGuid>58dbaa8d-3553-4632-89ad-fa51a45cb024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'alcohol-legals' and @name = 'alcohol-legals' and @type = 'checkbox']</value>
      <webElementGuid>ef062831-313e-48b1-a83d-0553e6453375</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
