<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tout accepter</name>
   <tag></tag>
   <elementGuidId>ef4c87c5-d6f8-4491-b1da-5880110c7865</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='didomi-notice-agree-button']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#didomi-notice-agree-button > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4e37e6c3-0f87-4446-86fa-9cc9f3510abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tout accepter</value>
      <webElementGuid>5bf51cde-0bf2-4a9e-adbb-fde3e1feac35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;didomi-notice-agree-button&quot;)/span[1]</value>
      <webElementGuid>6200ce5e-25d2-4a0e-b5d0-45c9f3f27783</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='didomi-notice-agree-button']/span</value>
      <webElementGuid>f9a35867-353a-4caa-bff6-9f67b98dbab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paramétrer mes choix'])[1]/following::span[1]</value>
      <webElementGuid>e03668fb-bee5-4b10-bda7-f3a8c24c575e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Voir nos partenaires'])[1]/following::span[2]</value>
      <webElementGuid>02bf0d65-0e5f-42d3-9a10-439d2a95e613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contenu principal'])[1]/preceding::span[1]</value>
      <webElementGuid>39e6d119-111a-4d0f-9b79-d38c9e2ad024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Croix'])[1]/preceding::span[1]</value>
      <webElementGuid>57e4c9ae-6afa-4b09-bb64-6539508b262d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span</value>
      <webElementGuid>c8ea974a-21aa-4c97-8502-f0142e2302ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Tout accepter' or . = 'Tout accepter')]</value>
      <webElementGuid>15a6b9a7-f768-4ebf-9e95-51eadbb6213d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
