<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Certifi par 135590 avis_getting-started-media</name>
   <tag></tag>
   <elementGuidId>8ab5170c-9474-424c-bc24-3f8bc20e24fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/div/div/div[2]/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.getting-started-media</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5de0e05e-03c0-47ca-a590-4899cf45bd16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>100vw</value>
      <webElementGuid>e89b6e85-c680-48c5-ba7b-9fba270379af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://eu-images.contentstack.com/v3/assets/blta867006d326c1e47/blt3b7492f876e3bd8a/getting-started-narrow?width=600&amp;auto=webp&amp;format=jpg&amp;quality=90</value>
      <webElementGuid>abc34cc5-c75a-4c30-af1e-6166d3c23cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://eu-images.contentstack.com/v3/assets/blta867006d326c1e47/blt3b7492f876e3bd8a/getting-started-narrow?width=375&amp;auto=webp&amp;format=jpg&amp;quality=90 375w, https://eu-images.contentstack.com/v3/assets/blta867006d326c1e47/blt3b7492f876e3bd8a/getting-started-narrow?width=600&amp;auto=webp&amp;format=jpg&amp;quality=90 600w, https://eu-images.contentstack.com/v3/assets/blta867006d326c1e47/blt3b7492f876e3bd8a/getting-started-narrow?width=750&amp;auto=webp&amp;format=jpg&amp;quality=90 750w</value>
      <webElementGuid>4213d833-44f5-49ef-8407-56a3ea66ac30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>getting-started-media</value>
      <webElementGuid>2a978b2b-bbdb-4978-8cfd-c272aed9c6fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;home-page page-layout&quot;]/div[@class=&quot;pre-home&quot;]/div[@class=&quot;getting-started&quot;]/picture[1]/img[@class=&quot;getting-started-media&quot;]</value>
      <webElementGuid>77726452-7ac6-4651-88b0-da64bda601c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div/div/div[2]/picture/img</value>
      <webElementGuid>95de86f8-0052-4505-aae7-42ec43455eb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Certifié par 135590 avis'])[1]/following::img[1]</value>
      <webElementGuid>ab6534b7-04b6-4217-b81d-50f6089d7911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/5'])[1]/following::img[1]</value>
      <webElementGuid>aaddac5b-c4e9-4dd0-9bbb-805272e17b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='les novices'])[1]/preceding::img[1]</value>
      <webElementGuid>a5783c7a-adeb-44da-b106-ab16aa50e0bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://eu-images.contentstack.com/v3/assets/blta867006d326c1e47/blt3b7492f876e3bd8a/getting-started-narrow?width=600&amp;auto=webp&amp;format=jpg&amp;quality=90')]</value>
      <webElementGuid>57cd8b57-9038-4a10-afc3-dcb873f54f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//picture/img</value>
      <webElementGuid>915c53e2-4028-4783-9248-fe88613ad7ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://eu-images.contentstack.com/v3/assets/blta867006d326c1e47/blt3b7492f876e3bd8a/getting-started-narrow?width=600&amp;auto=webp&amp;format=jpg&amp;quality=90']</value>
      <webElementGuid>8a86cf2a-ed75-4a53-8067-f3977af3f54f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
