<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rechercher un code postal ou une vill_cf4ae2</name>
   <tag></tag>
   <elementGuidId>8fb172c0-9971-43d1-aa28-f8c5474fa137</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='locator-search-term']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#locator-search-term</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9e8154ab-e43f-457b-98a0-38e3952ca6cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>locator-search-term</value>
      <webElementGuid>6d9a797f-8897-4516-a7cf-19f6b1c46bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>locator-search-term-suggestion</value>
      <webElementGuid>570503d3-12d4-4109-905d-1c6d8c4fa284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>locator-search-term-message</value>
      <webElementGuid>6a42c693-826e-4d88-acc6-5bfc5bb798d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>27fc3131-9d6c-413e-ab0a-a09c81303c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>cd27e834-6891-4f79-a2b0-7e627c9f26d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>postal-code</value>
      <webElementGuid>63ce0f50-404e-4f2f-9c79-52528df678d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search-term</value>
      <webElementGuid>e16aefbc-3d80-4530-a7cb-f3421143cd79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Code postal, ville…</value>
      <webElementGuid>f642bf7a-52f9-4988-aeeb-507689c1c294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b8493992-ed57-480a-8f70-7e9ee1761222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focus-visible</value>
      <webElementGuid>1ba60890-2843-45fd-bf84-427fd9c9df48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locator-search-term&quot;)</value>
      <webElementGuid>b38b1694-8090-40f3-a735-dcbd5ce802c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='locator-search-term']</value>
      <webElementGuid>21e6b09d-d273-4ace-b1d9-9e5dedf58d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div/div/div[2]/div/div/div/div/div/form/div/div/input</value>
      <webElementGuid>1a73477f-85c5-4960-a0ab-0e81399bdc47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rechercher un code postal ou une ville'])[1]/following::input[1]</value>
      <webElementGuid>8253c4ea-160c-47f2-bd90-88f27c0c57e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='du bon temps'])[1]/following::input[1]</value>
      <webElementGuid>eeb07f6f-7a0d-4fb2-8455-52708f2b837b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Réinitialiser'])[2]/preceding::input[1]</value>
      <webElementGuid>a0686ec0-c5f8-4f40-bcad-15f8bf5d3eff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Géolocalisation'])[1]/preceding::input[1]</value>
      <webElementGuid>eb64c692-9790-4f5e-8dc9-2b55c03fc67e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/form/div/div/input</value>
      <webElementGuid>94f38780-3b97-4f0f-9a8f-92b9a581b958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'locator-search-term' and @name = 'search-term' and @placeholder = 'Code postal, ville…' and @type = 'text']</value>
      <webElementGuid>9f95365e-030d-4f13-8073-074ee6eb28fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
