<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mark_Croix</name>
   <tag></tag>
   <elementGuidId>61979b98-3d35-4c00-9b57-ce48ee9e421b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='locator-search-term-suggestion']/div/ul/li/button/span/mark</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mark</value>
      <webElementGuid>d779d9bc-61fd-47f9-8075-14242eb9f0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Croix</value>
      <webElementGuid>885750f7-9cb6-4538-b3d7-f08e43065ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locator-search-term-suggestion&quot;)/div[@class=&quot;locator-search-suggestions&quot;]/ul[@class=&quot;locator-search-list&quot;]/li[1]/button[@class=&quot;suggestion-item&quot;]/span[@class=&quot;label&quot;]/mark[1]</value>
      <webElementGuid>27b2ddcd-5c79-448b-a7e7-86773cc62406</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='locator-search-term-suggestion']/div/ul/li/button/span/mark</value>
      <webElementGuid>04d3cf06-dd3f-4c04-8634-334b9cd46dc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Je trouve mon Chronodrive'])[1]/following::mark[1]</value>
      <webElementGuid>d7184212-eade-4dab-a3db-ec7251093c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Réinitialiser'])[2]/following::mark[1]</value>
      <webElementGuid>7383a2d8-1e53-4276-8535-7cce32748db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Croix'])[2]/preceding::mark[1]</value>
      <webElementGuid>9af077a2-8aab-42d4-b789-0fb86eaa9c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mark</value>
      <webElementGuid>329dad3c-96db-40d1-8001-2d30b91e0986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mark[(text() = 'Croix' or . = 'Croix')]</value>
      <webElementGuid>f30a6f5b-3572-474a-90e2-09d7988af5e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
