<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>2fd89e38-4614-446d-862a-fa4005fd81e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='line-4356']/article/div/div/div/span[3]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot; Pomme de terre à chair ferme blonde&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>674a9433-e790-479f-aeb3-18233a24bee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static1.chronodrive.com/img/PM/P/0/56/0P_4356.gif</value>
      <webElementGuid>dc39ed91-fb2d-4b56-adf0-ea686b63c89e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ad25d3af-493f-4302-8a45-3fe3b9ba3d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value> Pomme de terre à chair ferme blonde</value>
      <webElementGuid>a625bd6d-d20d-4c25-b738-0d41e09e3334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>eager</value>
      <webElementGuid>b926bb91-723d-4b9c-a8db-e929291053b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>74544f12-c5d1-49d9-845d-5165bf387e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>8a9a96c6-01a6-4c84-888a-b40b47e61cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;line-4356&quot;)/article[@class=&quot;product-card product-grid-card -layout-fluid -clickable&quot;]/div[@class=&quot;card-inner&quot;]/div[@class=&quot;card-content&quot;]/div[@class=&quot;card-extra&quot;]/span[@class=&quot;media&quot;]/img[1]</value>
      <webElementGuid>b29c47ab-6a23-488b-843d-84d541e4be49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='line-4356']/article/div/div/div/span[3]/img</value>
      <webElementGuid>f116c264-13ef-4457-88b9-2e465e655db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FRANCE'])[1]/following::img[1]</value>
      <webElementGuid>ac0d96f6-4cd4-4e76-a0b3-d9ac23589037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tomates'])[2]/following::img[1]</value>
      <webElementGuid>fcda62cb-427e-4824-a101-86c4c4f9c9e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C’est de saison'])[1]/preceding::img[1]</value>
      <webElementGuid>8d4f9924-b540-4ee2-8388-b77b90931389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frais'])[1]/preceding::img[1]</value>
      <webElementGuid>51b8681d-7b18-40ba-99b4-1a8082c8fd81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt=' Pomme de terre à chair ferme blonde']</value>
      <webElementGuid>81ab0180-65bc-47d2-bdbc-e6d5133896e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/img</value>
      <webElementGuid>388f0648-3298-472b-b55a-893689b8ab69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://static1.chronodrive.com/img/PM/P/0/56/0P_4356.gif' and @alt = ' Pomme de terre à chair ferme blonde']</value>
      <webElementGuid>26b7cc1e-d25a-4602-813d-a07d8cd2c9a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
